Navegación entre pantallas con menú principal
MiM14/custom_newspaper pull request #12
Opened 2022-11-20 14:14 UTC by MiM14

## Description de la tarea

Desarrollo de la estructura y las distintas vistas que formaran la aplicación y el menú principal que permitirá visualizar cada una de ellas

## ¿Cómo se ha implementado?

He creado una Main Activity y varios fragmentos uno para el listado de noticias, otro para las gestión de RSS y el ultimo para un perfil, y utilizando el Main Activity como FragmentContainerView donde irán cargando las distintas vistas. El enlace entre estas es una barra de navegación en la parte inferior con las 3 opciones y sus respectivos iconos. 

Además he añadido unos extras, como son un item para el recycler view de la feed, un theme y colores sacados de [aquí](https://m3.material.io/theme-builder#/dynamic) y unas toolbars que en un principio solo uso para diferenciar una vista de otra.

Safe Args esta añadido añadido al proyecto, pero de momento no se esta utilizando

#### Disclaimer
Disculpas por el tamaño de la pr no he visto manera de acortar aun así comentar que muchas de las líneas y archivos son
imágenes, valores o Gradle

## Keywords
- UI
- Navigation
- Fragment
- BottomNavigationView
- SafeArgs
- Material3
- Menu

## Screenshots or Video
### Vistas
![image](https://user-images.githubusercontent.com/85709107/202907014-07b8b34f-49f8-47a6-89c1-8fc831c5bde3.png)

### Vídeo
https://user-images.githubusercontent.com/85709107/202907029-2d536c95-111e-41fc-b687-dc858f5a8abd.mp4

## Objetivos

## Criterios de Evaluación

2022-11-21 10:35 UTC, albertoag128 submitted a review, later dismissed
Voy dejando aqui todos los comentarios dado que al haberse realizado varios commits, es la única forma que tengo de ver todos los cambios a la vez.

-- Sugerencia: En el MainActivity, si quieres puedes crear funciones para cada opcion del when. Sería una forma de modularizar el código por si en el futuro hay  cambios pero es una sugerencia NO ES UN ERROR.
-- Sugerencia: Si te sientes más cómodo puedes modificar los estilos (themes) para combinar una serie de colores que funcionen en conjunto. No se si utiliaras los 70 colores que has añadido, pero quizás sean demasiados (hago incapié en que no estoy al tanto de si utilizas todos, y si así fuera, no tengo nada que decir).
-- Sugerencia: Siento ser tan "molesto", pero con respecto al archivo item_rss_feed, el issue no incluye realizar el diseño de cada item rss. Yo personalmente lo veo bien para realizar pruebas para ver como queda con herramientas como tools, pero el problema de añadirlo aqui es que quizás aumenta el tamaño de la pr. Yo no lo veo como fallo y entiendo lo que has hecho, pero quizás no sea contenido de este issue.
-- Sugerencia: ahora quizás el proyecto no es muy grande, pero si que se contempla el hecho de implementar una navegación segura con safe args, para que si la aplicación escala, se eviten conflictos de missing views de cara al futuro.


Por todo lo demás yo considero que es un buen trabajo y doy por aprobada esta pr. Enhorabuena Ismael, independientemente de los comentarios y sugerencias, consigues lo que se propone en la pr.

2022-11-24 15:26 UTC, MiM14 commented on app/src/main/java/com/example/rss_aggregator_2022/MainActivity.kt
> +        findViewById<BottomNavigationView>(R.id.bottom_navigation).setOnItemReselectedListener {
Esto ya esta corregido en otra pr, funcionaba igual pero con 2 click en vez de 1

Reselect -> Select

2022-11-30 22:23 UTC, josem-perram requested changes
Dejo comentarios de cosas que faltan por implementar y.... de cosas que se han implementado sin ser pedidas en el ticket. Hay que tener mucho cuidado con esto porque se da una estimación de la tarea NO real ya que se ha estimado una cosa y se ha desarrollado otra.

2022-11-30 22:23 UTC, josem-perram commented on app/src/main/java/com/example/rss_aggregator_2022/MainActivity.kt
> +                R.id.to_rss_feed_item -> findNavController(R.id.main_fragment_view).navigate(R.id.feed)
ok, añade la navegación segura, navegar con IDs no es usar navegación segura.

2022-11-30 22:23 UTC, josem-perram commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_width="match_parent"
Al ubicarlo con Constraints, deberíamos "anular" el width y ajustarlo al start y end del parent.

2022-11-30 22:23 UTC, josem-perram commented on app/src/main/res/layout/bottom_navigation_view.xml
> +<?xml version="1.0" encoding="utf-8"?>
No entiendo para qué es esta vista.

2022-11-30 22:23 UTC, josem-perram commented on app/src/main/res/layout/fragment_rss_feed.xml
> +    <androidx.recyclerview.widget.RecyclerView
Esto no se solicitaba en el ticket, ha incrementado las funcionalidades y la estimación de la tarea sin ser necesario.

2022-11-30 22:23 UTC, josem-perram commented on app/src/main/res/layout/item_rss_feed.xml
> +<androidx.cardview.widget.CardView xmlns:android="http://schemas.android.com/apk/res/android"
Esto no se solicitaba en el ticket, ha incrementado las funcionalidades y la estimación de la tarea sin ser necesario.

2022-11-30 22:23 UTC, josem-perram commented on app/src/main/res/navigation/nav_graph.xml
> +<navigation xmlns:android="http://schemas.android.com/apk/res/android"
Falta añadir la navegación segura. Los actions de la navegación del menú irían dentro del elemento <navigation ...> aqui </navigaton>. Al estar ubicado aquí, cualquier fragment tiene acceso a estos actions.

2022-12-01 08:24 UTC, MiM14 commented on app/src/main/res/layout/bottom_navigation_view.xml
> +<?xml version="1.0" encoding="utf-8"?>
En uno de los primeros commit pretendía usarla con un include, al final vi que no era util y lo metí directamente en el activity main, mientras intente solventar mis problemas con git debió colarse de nuevo.

2022-12-01 08:48 UTC, MiM14 commented on app/src/main/res/layout/item_rss_feed.xml
> +<androidx.cardview.widget.CardView xmlns:android="http://schemas.android.com/apk/res/android"
Totalmente de acuerdo, lo hice más que nada por estética y por empezar a diseñar la aplicación. Debí haber considera antes la sugerencia que me hizo previamente Alberto y haberlo quitado. Sin embargo, debido a que ya esta hecho y corregido mi intención dejarlo.

Procurare que no vuelva a ocurrir en el futuro, gracias por los comentarios.

2022-12-01 09:47 UTC, albertoag128 commented on app/src/main/java/com/example/rss_aggregator_2022/MainActivity.kt
> +                R.id.to_rss_feed_item -> findNavController(R.id.main_fragment_view).navigate(NavGraphDirections.toFeed())
--Sugerencia: por ejemplo si aquí sacaras cada una de las navegaciones a una función, además de modularizar el código, si más adelante quisieramos que otras interacciones del usuario navegaran a los mismos destinos a los que apunta navigation, podríamos reciclar esas funciones.

2022-12-01 09:56 UTC, albertoag128 commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_width="0dp"
Es buena práctica que tanto las dimensiones, colores, strings, etc vengan de resources. A mi a veces también se me pasa, échale un vistacillo.

2022-12-01 10:01 UTC, albertoag128 commented on app/src/main/res/layout/fragment_rss_management.xml
> +<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
Me falta un recycler view. Quizás esté yo equivocado pero según el modelo de figma, este xml debería de contener un recycler view con las rss que vamos agregando para poder gestionarlas.

![imagen](https://user-images.githubusercontent.com/91797204/205023863-1b7058f4-eb18-4eb5-ae3f-47ca6f07d73b.png)

2022-12-01 10:01 UTC, albertoag128 commented on app/src/main/res/layout/item_rss_feed.xml
> +            android:layout_width="0dp"
Lo mismo, ten cuidado con resources por favor.

2022-12-01 10:02 UTC, MiM14 commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_width="0dp"
Esta hecho así adrede:
https://github.com/MiM14/rss-aggregator/pull/15?notification_referrer_id=NT_kwDOBRvRM7M0OTY1NDAyMzA2Ojg1NzA5MTA3#discussion_r1036518121

2022-12-01 10:04 UTC, MiM14 commented on app/src/main/res/layout/fragment_rss_management.xml
> +<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
Esa tarea esta asignada a mi issue nº11 no a esta

2022-12-01 10:05 UTC, MiM14 commented on app/src/main/java/com/example/rss_aggregator_2022/MainActivity.kt
> +                R.id.to_rss_feed_item -> findNavController(R.id.main_fragment_view).navigate(NavGraphDirections.toFeed())
Tienes razón buen apunte.
Muchas gracias.

2022-12-01 10:06 UTC, albertoag128 commented on app/src/main/res/layout/fragment_rss_management.xml
> +<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
Perdón, esta corrección no corresponde a este issue, pido disculpas.

2022-12-01 10:09 UTC, albertoag128 requested changes
En lineas generales se ve un buen trabajo, cambiame lo de resources y lo que ha mencionado Chema por favor. Sigue trabajando así Ismael, poco a poco iremos todos puliendo cosas y desarrollando apps mejor. Mucho ánimo!!

2022-12-01 10:11 UTC, albertoag128 commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_width="0dp"
Cierto es, no me había dado cuenta, ignora el comentario entonces.

2022-12-01 10:11 UTC, MiM14 commented on app/src/main/java/com/example/rss_aggregator_2022/MainActivity.kt
> +                R.id.to_rss_feed_item -> findNavController(R.id.main_fragment_view).navigate(NavGraphDirections.toFeed())
Ya lo he añadido

2022-12-01 10:12 UTC, albertoag128 commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_width="0dp"
De todas formas si que quedan algunas unidades puestas en el xml como tal, echalas un vistacillo porfa.

2022-12-01 10:21 UTC, MiM14 commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_width="0dp"
Lol. Debido a un error que tuve parece que también había perdido el fichero dimen, muchas gracias Alberto.

2022-12-16 14:36 UTC, josem-perram approved these changes
🚀

2022-12-16 15:45 UTC, albertoag128 approved these changes
Lo veo todo bien, buen trabajo!!

2022-12-16 15:45 UTC, merged