Formulario de RSS
MiM14/custom_newspaper pull request #15
Opened 2022-11-30 18:17 UTC by MiM14

## Description de la tarea

Formulario de RSS. Creación de un formulario para que el usuario introduzca sus RSS

## ¿Cómo se ha implementado?

1.  He añadido una toolbar con un menu al fragment de management. Este menu tiene un único elemento, es visible siempre y se muestra con un icono (+).
2.  En el fragment de management se ha añadido un setUpView() que configura la Toolbar de momento. Y donde defino la utilidad del botón (+) de la toolbar que nos lleva a la vista UserFormFragment("Utilizando safe args")
3. El formulario esta compuesto de un titulo 2 input layout y 2 botones. El botón cancel al pulsar nos devuelve al management fragment y el botón guardar toma los datos de los inputs y los guardar en un xml.
4. Por ultimo pero no menos importante, para poder guardar he añadido 2 ficheros un management factory que por donde accedo a la capa datos. Y un ViewModel encargado de guardar los datos ingresados por el usuario mediante una corrutina IO, además de contar un model de UI que almacena el estado de la maquina

## Keywords

- Live

## Screenshots or Video

## Objetivos

## Criterios de Evaluación

2022-11-30 22:51 UTC, josem-perram requested changes
Ismael, revisa bien los comentarios porque hay cosas importante que debemos entender para poder asimilarlas y usarlas correctamente.

Por otro lado, tenemos que ver cómo trabajar con las PR y los tickets pues se están haciendo cosas que no se piden y la PR se convierte en un popurrí de cosas.

2022-11-30 22:51 UTC, josem-perram commented on app/src/main/java/com/example/rss_aggregator_2022/features/presentation/rssmanagement/RssManagementFactory.kt
> +    fun saveUserRss(sharedPreferences: SharedPreferences): RssManagementViewModel {
no entiendo por qué has usado este naming: ``saveUserRss``, por favor, aquí mejor usar algo como ``injectRssManagementViewModel``.

2022-11-30 22:51 UTC, josem-perram commented on app/src/main/java/com/example/rss_aggregator_2022/features/presentation/rssmanagement/RssManagementViewModel.kt
> +    private val rssManagementPublisher: MutableLiveData<RssUiState> by lazy {
Si haces privado el LiveData, cómo va a ser accesible por el Fragment??

2022-11-30 22:51 UTC, josem-perram commented on app/src/main/java/com/example/rss_aggregator_2022/features/presentation/rssmanagement/RssManagementFragment.kt
> +class RssManagementFragment : Fragment() {
Donde hacemos la acción de escuchar el LiveData del ViewModel ??

2022-11-30 22:51 UTC, josem-perram commented on app/src/main/java/com/example/rss_aggregator_2022/features/presentation/rssmanagement/UserFormFragment.kt
> +            RssManagementFactory().saveUserRss(it.getPreferences(Context.MODE_PRIVATE))
Por qué usas un ViewModel que está asociado a otro fragmento?? RssManagementFragment. Cada fragmento tiene su ViewModel. UserFormFragment debería tener un viewmodel con la operación de almacenar un RSS.

2022-11-30 22:51 UTC, josem-perram commented on app/src/main/java/com/example/rss_aggregator_2022/features/presentation/rssmanagement/RssManagementViewModel.kt
> +    fun saveRss(name: String, url: String) {
Esta acción tiene sentido aquí?? es decir, si esta vista es para mostrar un listado de RSS y abrir un bottomSheet, para qué quiero tener una función que me almacena RSS??

2022-11-30 22:51 UTC, josem-perram commented on app/src/main/java/com/example/rss_aggregator_2022/features/presentation/rssmanagement/UserFormFragment.kt
> +                showSnackBar()
Por qué visualizas un mensaje de que se ha añadido un registro sin saber si es cierto?? por qué crees que se ha añadido correctamente??

2022-11-30 22:51 UTC, josem-perram commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_width="@dimen/zero_size"
por qué usamos dimens?? Usamos dimens porque Android nos permite tener el mismo fichero dimens con las mismas claves pero con valores diferentes y cargarlos según la densidad de la pantalla 1200x1920, etc. 
Ejemplo: dimens.xml y sw-800/dimens.xml 
**dimens.xml**
<dimen id="size_image">150dp</dimen>

**sw-800/dimens.xml** (para pantallas con resolución mayor a 800)
<dimen id="size_image">300dp</dimen>

Misma clave del dimens: "size_image" pero se carga el fichero dimens.xml según la resolución del móvil o tablet.

Es por esto que no es necesario crear un dimens para 0dp ya que 0dp será igual para todos los dispositivos.

2022-11-30 22:51 UTC, josem-perram commented on app/src/main/res/layout/fragment_profile.xml
>  <androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
Esto no se pide en el ticket.

2022-11-30 22:51 UTC, josem-perram commented on app/src/main/res/layout/fragment_rss_feed.xml
> +    <androidx.appcompat.widget.Toolbar
Esto no se pide en el ticket.

2022-11-30 22:51 UTC, josem-perram commented on app/src/main/res/layout/fragment_rss_management.xml
> +    <androidx.appcompat.widget.Toolbar
Esto no se pide en el ticket

2022-11-30 22:51 UTC, josem-perram commented on app/src/main/res/layout/user_form_view.xml
> +<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
El naming debería ser algo como fragment_user_form, los bottomsheet son fragmentos

2022-11-30 22:51 UTC, josem-perram commented on app/src/main/res/menu/management_menu.xml
> +        android:title="@string/Add_option"
en minúsculas las claves.

2022-11-30 22:51 UTC, josem-perram commented on app/src/main/res/navigation/nav_graph.xml
> +    <action
Esto debería estar hecho en la anterior PR

2022-11-30 22:51 UTC, josem-perram commented on app/src/main/res/navigation/nav_graph.xml
> +        android:name="com.example.rss_aggregator_2022.features.presentation.rssfeed.RssFeedFragment"
No me he dado cuenta antes, pero lo packages en java se separan con puntos y no se usa underscore _, quizás deberías haberlo llamado rssagregator, sin mas.

2022-11-30 22:51 UTC, josem-perram commented on app/src/main/java/com/example/rss_aggregator_2022/features/presentation/rssmanagement/UserFormFragment.kt
> +                findNavController().navigateUp()
Si usas navigateUp, para qué has creado el action en el grafo de navegación?? No te haría falta.

2022-11-30 22:52 UTC, josem-perram requested changes
Ismael, revisa bien los comentarios porque hay cosas importante que debemos entender para poder asimilarlas y usarlas correctamente.

Por otro lado, tenemos que ver cómo trabajar con las PR y los tickets pues se están haciendo cosas que no se piden y la PR se convierte en un popurrí de cosas.

2022-11-30 23:45 UTC, MiM14 commented on app/src/main/res/navigation/nav_graph.xml
> +    <action
Tienes toda la razón, lo añadire en una pr aparte para no mezclar

2022-11-30 23:45 UTC, MiM14 commented on app/src/main/res/navigation/nav_graph.xml
> +        android:name="com.example.rss_aggregator_2022.features.presentation.rssfeed.RssFeedFragment"
Gracias, por el comentario en la misma pr en la que solucione, los safe args y el ReSelect tratare de colocar todo de una manera más adecuada.

2022-11-30 23:54 UTC, MiM14 commented
He solventado la mayoría de problemas que me planteas @josem-perram, que espero haber corregido exitosamente.

Te estoy agradecido por los comentarios y espero no volver a cometerlos de ahora en adelante

2022-12-01 08:51 UTC, MiM14 commented on app/src/main/res/navigation/nav_graph.xml
> +        android:name="com.example.rss_aggregator_2022.features.presentation.rssfeed.RssFeedFragment"
Planeo añadir un PR ordenando el proyecto, lo tendré en cuenta. Mil gracias.

2022-12-01 10:16 UTC, albertoag128 commented on app/src/main/java/com/example/rss_aggregator_2022/features/rssmanagement/RssManagementFactory.kt
> +    fun injectRssManagementViewModel(sharedPreferences: SharedPreferences): UserFormViewModel {
--Sugerencia: esta todo perfecto, pero te puedo preguntar por que lo de inject? No sería más correcto un get dado que la función devuelve un view model?

2022-12-01 10:23 UTC, albertoag128 commented on app/src/main/java/com/example/rss_aggregator_2022/features/rssmanagement/RssManagementFragment.kt
> +                            actionManagementToUserForm()
Intentar implementar navegación segura por favor

2022-12-01 10:30 UTC, albertoag128 approved these changes, later dismissed
Por lo que he visto, casi todo bien. Buen trabajo!!

2022-12-12 09:46 UTC, albertoag128 approved these changes
Por lo que veo, los cambios sólo están relacionados con un renaming asi que todo ok

2022-12-16 14:39 UTC, josem-perram approved these changes
🚀 Cambia lo hablado ASAP

2022-12-16 16:08 UTC, merged