Vista con el listado de RSS introducidos por el Usuario
MiM14/custom_newspaper pull request #26
Opened 2022-12-16 13:46 UTC by MiM14

## Description de la tarea

Visualización del listado con las rss introducidas por el usuario

## ¿Cómo se ha implementado?

## Keywords

## Screenshots or Video

## Objetivos

## Criterios de Evaluación

2022-12-20 15:45 UTC, Joelgh1 commented on app/src/main/java/com/example/rss_aggregator_2022/features/rssmanagement/RssManagementViewModel.kt
> +                        ManagerUiState(managerFeed = feed, error = null)
Como el valor por defecto del error es null no hace falta que se lo pases

2022-12-20 15:47 UTC, Joelgh1 approved these changes
Todo Ok

2022-12-20 16:24 UTC, MiM14 commented on app/src/main/java/com/example/rss_aggregator_2022/features/rssmanagement/RssManagementViewModel.kt
> +                        ManagerUiState(managerFeed = feed, error = null)
Lo puse por poner y tienes razón, no hace falta. Lo corregiré más adelante

2022-12-20 18:46 UTC, Joelgh1 requested changes

2022-12-20 18:46 UTC, Joelgh1 commented on app/src/main/java/com/example/rss_aggregator_2022/features/rssmanagement/RssManagementFragment.kt
> +                    uiState.error.let {
Esta dos veces

2023-01-07 15:33 UTC, josem-perram approved these changes
🚀

2023-01-09 14:55 UTC, merged