Guardar RSS (Data)
MiM14/custom_newspaper pull request #8
Opened 2022-11-16 18:24 UTC by MiM14

## Description de la tarea

 Implementación las clases necesarias para guardar un RSS (URL, name) introducido por el usuario.

## ¿Cómo se ha implementado?

A la hora de implementar la fuente de datos local mi objetivo ha sido optimizar mi tiempo al máximo y así poder dedicarle más tiempo a otras funcionalidades. Por ello decido optar por utilizar SharedPreference. Sin embargo, en caso de necesitar otro tipo de fuente de datos creo un repositorio LocalDataSource, evitando posibles problemas a futuro

Para guardar los datos introducidos por el usuario en un xml local utilizo shared preference y un genérico, KSerializer, para meter los datos name y url en un JSON.

Además también he cambiado los naming de alguno métodos con el fin de que se sobrentiendan mejor.

Either no es necesario para este caso, pero ya estaba añadido desde la issue2_api_client

## Keywords

- Shared Preference
- Either
- Repository

## Objetivos

## Criterios de Evaluación

2022-11-17 16:33 UTC, HectorMartin4 approved these changes
Todo OK

2022-11-23 14:58 UTC, HectorMartin4 approved these changes, later dismissed
Vale, perfecto

2022-11-30 22:15 UTC, josem-perram requested changes
Ismael, no veo la necesidad de crear un objeto para su posterior serialización. Please, revisa el comentario.

2022-11-30 22:15 UTC, jmperezra commented on app/src/main/java/com/example/rss_aggregator_2022/features/data/local/LocalDataSource.kt
> +interface LocalDataSource {
Me gusta que hayas argumentado la creación de esta interfaz por si en un futuro decides cambiar de XML a otra fuente.

2022-11-30 22:15 UTC, josem-perram commented on app/src/main/java/com/example/rss_aggregator_2022/features/data/local/xml/XmlLocalDataSource.kt
> +        editor.putString(urlRss, kSerializer.toJson(Rss(name,urlRss),Rss::class.java))
Por qué te creas un objeto para serializarlo?? Por qué no usas como key la url y como value el name ??

2022-12-02 12:16 UTC, MiM14 commented on app/src/main/java/com/example/rss_aggregator_2022/features/data/local/LocalDataSource.kt
> +interface LocalDataSource {
Ya esta corregido, además de eso he borrado Gson del gradle y el KSerializer porque ahora están en desuso.

2022-12-16 14:33 UTC, josem-perram approved these changes
🚀

2022-12-16 15:07 UTC, HectorMartin4 approved these changes
ok!

2022-12-16 15:07 UTC, merged